title: code.jefflaplante.com
description: >
  code.jefflaplante.com
copyright: 2017 Jeff LaPlante
sass:
  sass_dir: assets/sass
url: http://code.jefflaplante.com
disqus_shortname: 
facebook_username:
twitter_username: "@jefflaplante"
linkedin_username: "jefferylaplante"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "jefflaplante"
feed_icon: rss
email: "#"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
